apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://$PROMETHEUS_HOSTPORT
    isDefault: true
    editable: true

  - name: Loki
    uid: Loki
    type: loki
    access: proxy
    url: http://$LOKI_HOSTPORT
    editable: true
