{
 "title": "FlowLoad",
 "tags": [
  "k6",
  "load-testing",
  "flowload"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "testid",
    "label": "testid",
    "query": {
     "query": "label_values(k6_http_reqs_total, testid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs_total{testid=~\"$testid\"}[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(k6_http_req_failed_rate{testid=~\"$testid\"})",
     "legendFormat": "HTTP failed rate"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(k6_http_req_duration_milliseconds_p95{testid=~\"$testid\"})",
     "legendFormat": "p95"
    },
    {
     "expr": "avg(k6_http_req_duration_milliseconds_p99{testid=~\"$testid\"})",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Virtual Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(k6_vus{testid=~\"$testid\"})",
     "legendFormat": "VUs"
    }
   ]
  },
  {
   "title": "k6 Run Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"k6\", project=\"flowload\", testid=~\"$testid\"}"
    }
   ]
  }
 ]
}